### ISSUE TITLE
set RAM percentage java opts for OpenSearch

### ISSUE THREAD

**Issue by rursprung** [Opster/opensearch-k8s-operator#171]
coming from this comment thread: https://github.com/Opster/opensearch-k8s-operator/pull/157#discussion_r884127121

instead of documenting how RAM settings for the JVM can be manually set they should instead be set by default - and as percentage values rather than absolute values.

a good starting point might be `-XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=30`, as it's in line with the statement that 50% of the RAM should be left for the OS to manage file system operations (and on k8s this must be reserved within the pod as otherwise there's no guarantee that the RAM will be free).

some documentation on these parameters can be found e.g. here:
* https://www.baeldung.com/java-jvm-parameters-rampercentage
* https://docs.microsoft.com/en-us/azure/developer/java/containers/overview

**Comment by prudhvigodithi** [comment]
Hey @rursprung, good idea, but ideally we should have flexibility for the user to define, else with a condition we should go with `XX:MaxRAMPercentage` and `XX:InitialRAMPercentage`. Thoughts?
@swoehrl-mw @idanl21 @segalziv @dbason

**Comment by segalziv** [comment]
I'll break my comment into two. in general, I think that it is a good thing to allow users to specify any JVM parameter they wish for so that there will no limitation to customize as you wish.

Specifically regarding the `XX:MaxRAMPercentage` and `XX:InitialRAMPercentage` I'm not sure this is the best practice. the official documentation recommends using Xms and Xmx ([for example](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L132)), and as the docs state "It's important to note that the JVM ignores InitialRAMPercentage when we configure the -Xms option." so that can cause confusion.

**Comment by swoehrl-mw** [comment]
I agree that we should give users the option of setting their own JVM options and to override the heap size if they want. Unless there are good arguments against `XX:MaxRAMPercentage` and `XX:InitialRAMPercentage` I think I would prefer them as then we do not have to calculate `Xmx` and `Xms` in the operator but just pass the percentage.

**Comment by idanl21** [comment]
Hey @rursprung, honestly i didn’t know the `XX:MaxRAMPercentage` option, i agree we have to give the users the choose which option they want, just for understanding, the Percentage are taken from the limit or the request?
by the way, you can always create a PR that implement that behaviour :)

**Comment by ibotty** [comment]
Shouldn't the memory settings come from the resource limits?  Java is pretty good in obeying them when configured accordingly.

**Comment by rursprung** [comment]
> just for understanding, the Percentage are taken from the limit or the request?

the limits. see also here: https://stackoverflow.com/questions/65167422/java-10-xxmaxrampercentage-flag-in-kubernetes-container/65168058#65168058

> by the way, you can always create a PR that implement that behaviour :)

i know :)
but alas, i sadly don't have the time right now (and it'd take me more time as this would be my first contribution to a project written in Go and to my first k8s operator, so i'd have to dig into it first).

> Shouldn't the memory settings come from the resource limits?

java indeed has some heuristics for calculating the max. heap size, however these might not yield the results which were expected. esp. with OpenSearch (and Elasticsearch) the recommendation is to leave half the memory for the OS to do file-system caching and this is not something considered by the JVM:
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/tune-for-search-speed.html#_give_memory_to_the_filesystem_cache_2 (i couldn't find the equivalent documentation from OpenSearch...)

**Comment by ibotty** [comment]
The recommendation is not applicable to Kubernetes, because without additional config, kubernetes will just schedule other work on the node and opensearch nodes will get starved if configured as if it's the only thing running on the host.  For Kubernetes **the only reasonable thing** is configuring out of the resource limits and requests.

**Comment by idanl21** [comment]
marged

**Comment by rursprung** [comment]
> marged

@idanl21: where/when? i don't find e.g. `MaxRAMPercentage` anywhere in the code (using the GitHub search)?
