### ISSUE TITLE
Unable to create appropriate roles coordinator node 

### ISSUE THREAD

**Issue by karthikbattaram** [Opster/opensearch-k8s-operator#187]
Hi

So while trying to deploy opensearch cluster using the operator, in the yaml of type OpesearchCluster which is used to deploy the cluster, under nodePools section, the roles for coordinator nodes is supposed to be empty in order to have dedicated coordinator nodes, but upon setting this to empty, the node assumes all roles (master, data, ingest). 

Are we missing something here, is there some way to have dedicated coordinator nodes(nodes that dont have any role configured)

**Comment by swoehrl-mw** [comment]
Hi @karthikbattaram. Thanks for reporting this issue.
As the operator is implemented the roles for a node are configured using an environment variable. 
The underlying issue seems to be https://github.com/opensearch-project/OpenSearch/issues/3412, opensearch cannot distinguish betwen the node roles not set at all and set to an empty list so if the operator sets an empty string it is treated as the node roles environment variable not being available and the node assumes all roles.

As a workaround you could give the nodepool the ingest role (asuming you do not use ingest in your cluster).
