### ISSUE TITLE
Dashboard not connecting when trying to use something other than default security

### ISSUE THREAD

**Issue by jonathon2nd** [Opster/opensearch-k8s-operator#340]
I opened an issue here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2712
But I think I may have opened it in the wrong repo :/

TLDR; trying to set different `admin` and `dashboarduser` passwords causes dashboard to not connect after the cluster is up and ready.

Any input would be greatly appreciated :D

**Comment by swoehrl-mw** [comment]
Hi @jonathon2nd
I think I see the issue: You are supplying the new/changed password for dashboards via `additionalConfig`. This is not only insecure (as the password is written in cleartext), it is also overwritten because the operator supplies the password via envvar.
Please create a secret with your changed credentials that dashboards should use (keys `username` and `password`) and then set `dashboards.opensearchCredentialsSecret` like this:
```yaml
spec:
  dashboards:
    opensearchCredentialsSecret:
      name: dashboards-credentials
```

Can you please try if this approach solves your problem?

**Comment by idanl21** [comment]
Hey @jonathon2nd, cam you please share here your Yaml file?

**Comment by jonathon2nd** [comment]
[opensearch-example.txt](https://github.com/Opster/opensearch-k8s-operator/files/9930563/opensearch-example.txt)
I was able to use this, hash your own passwords in the node pod 
`[opensearch@my-cluster-masters-0 ~]$ /usr/share/opensearch/plugins/opensearch-security/tools/hash.sh `

**Comment by swoehrl-mw** [comment]
@jonathon2nd 
Good to know it worked for you.
I've made a note to add this to the docs (I've got a revamp of the usergide planned anyway).

Closing this as completed.
