### ISSUE TITLE
Currently opensearch-operator does not support annotations for services, so can we support the same?

### ISSUE THREAD

**Issue by Gm101** [Opster/opensearch-k8s-operator#526]
Hi Team,
Currently, the annotations can only be added to the [node pools](https://github.com/Opster/opensearch-k8s-operator/blob/main/charts/opensearch-operator/files/opensearch.opster.io_opensearchclusters.yaml#L4202) & [dashboards](https://github.com/Opster/opensearch-k8s-operator/blob/main/charts/opensearch-operator/files/opensearch.opster.io_opensearchclusters.yaml#L2029) but not for services for opensearch-dashboard & opensearch-cluster. Looking at the [NewServiceForCR function in the cluster.go file](https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/builders/cluster.go#L590),  I found that opensearch-operator does not support annotations for services.
So can we please support the same?

**Comment by mskdenigma** [comment]
An example of this being an issue is when using contour/envoy Ingresses.  When attempting to expose the REST api http endpoint externally we grant a cert to that ingress however because Opensearch starts with https enabled you need to set an annotation on the Service object because of the upstream tls. Here is the annotation:
`projectcontour.io/upstream-protocol.tls: "9200"`

Being able to add annotations to the service would be great!

**Comment by swoehrl-mw** [comment]
Thanks for suggesting this @Gm101. I think this can be implemented relatively straightforward. Marking this as a feature request (contributions always welcome).
