### ISSUE TITLE
http: TLS handshake error from ${RANDOM_NODE}

### ISSUE THREAD

**Issue by kinseii** [Opster/opensearch-k8s-operator#599]
Hi all, OpenSearch operator deployed by Helm in Azure KS v.1.26.6. An error from the topic is observed in the operator logs.

```
$ kubectl logs opensearch-operator-controller-manager-744f5ccfdb-zqzn7 -n service
Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, operator-controller-manager
I0906 17:48:10.025498       1 main.go:186] Valid token audiences: 
I0906 17:48:10.025609       1 main.go:306] Generating self signed cert as no cert is provided
I0906 17:48:15.227188       1 main.go:356] Starting TCP socket on 0.0.0.0:8443
I0906 17:48:15.227409       1 main.go:363] Listening securely on 0.0.0.0:8443
2023/09/06 17:48:23 http: TLS handshake error from 10.0.178.148:51528: EOF
2023/09/06 17:48:23 http: TLS handshake error from 10.0.178.148:51526: EOF
```

If I remove the pod, the error changes to a different IP. I didn't find any correlation, so it seems to be a random IP from the OpenSearh cluster node pool.

As far as I can tell, this error does not affect the cluster, but I still wonder why this might be happening?

**Comment by swoehrl-mw** [comment]
Hi @kinseii. The kube-rbac-proxy is a HTTPS proxy for the metrics endpoint of the operator that also verifies authorization via Kubernetes RBAC. From your logs I'd say something in your cluster is trying to contact the proxy via HTTP instead of HTTPS (I'm pretty sure it is not something from opensearch). Do you have by chance metrics scraping enabled for the operator (either prometheus or Azure Monitor) without configuring the endpoint as HTTPS?

 > As far as I can tell, this error does not affect the cluster

Correct, operator functionality is not impacted by this.
